FROM confluentinc/cp-kafka-connect:latest

# Download Debezium connector manually
RUN mkdir -p /usr/share/confluent-hub-components/debezium-connector-postgresql && \
    curl -L https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgresql/2.6.1.Final/debezium-connector-postgresql-2.6.1.Final-plugin.tar.gz \
    | tar xz -C /usr/share/confluent-hub-components/debezium-connector-postgresql

# (Optional) Add Protobuf converter if needed
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-protobuf-converter:latest
